<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
      <div class="navbar-header active">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>"><span class="glyphicon glyphicon-home"> </span> Home</a>
      </div>
      <?php 
        if($this->user['type'] == "admin")
        {
          ?>
      <li><a href="<?php echo $this->baseUrl(); ?>/Admin">Admin</a></li>
      <?php
    }
    ?>
   <!--  <li>
         <a href="<!?php echo $this->baseUrl(); ?>">
          <span class="glyphicon glyphicon-tasks"> </span> Courses</a>

    </li> -->
     <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <?php
          foreach ($this->categories as $category) {
        ?>
          <li><a href="<?php echo $this->baseUrl(); ?>/course/list?id=<?php echo $category['id'] ?>"><?php echo $category['name'] ?> </a></li>
          <?php } ?>
        </ul>
      </li>
    </ul>
    </div>
    <div class="col-sm-3">
      
      <?php if(!$this->logged){
        ?>
     
        <dir class="navbar-right">
            <button type="button" class=" btn-link" data-toggle="modal" data-target="#login" ><span class="glyphicon glyphicon-log-in"></span> Login</button>| <button type="button" class=" btn-link" data-toggle="modal" data-target="#regist">Regist</button>
        </dir>
      
      <?php
    }
    else
    {
      ?>
        <dir class="navbar-right">
            <a href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
        </dir>
        <div class="col-sm-4 navbar-brand">
          <a href="<?php echo $this->baseUrl(); ?>/auth/home"><?php echo $this->user['name'];?></a>
        </div>
        <div class="col-sm-4">
          <img class="navbar-brand img-circle" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
        </div>
        
    <?php
    }
    ?>
    </div>
  </div>
</nav>

<!-- end nav -->



<br />
<div id="view-content" class="container">
	<!-- <p>View script for controller <b>Matrial</b> and script/action name <b>add</b></p> -->

	<h4>Add new Matrial for <?php  echo $this->cname ?></h4>
	<?php echo  $this->form ; ?>


</div>