<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
      <div class="navbar-header active">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>"><span class="glyphicon glyphicon-home"> </span> Home</a>
      </div>
      <?php 
        if($this->user['type'] == "admin")
        {
          ?>
      <li><a href="<?php echo $this->baseUrl(); ?>/Admin">Admin</a></li>
      <?php
    }
    ?>
   <!--  <li>
         <a href="<!?php echo $this->baseUrl(); ?>">
          <span class="glyphicon glyphicon-tasks"> </span> Courses</a>

    </li> -->
     <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <?php
          foreach ($this->categories as $category) {
        ?>
          <li><a href="<?php echo $this->baseUrl(); ?>/course/list?id=<?php echo $category['id'] ?>"><?php echo $category['name'] ?> </a></li>
          <?php } ?>
        </ul>
      </li>
    </ul>
    </div>
    <div class="col-sm-3">
      
      <?php if(!$this->logged){
        ?>
     
        <dir class="navbar-right">
            <button type="button" class=" btn-link" data-toggle="modal" data-target="#login" ><span class="glyphicon glyphicon-log-in"></span> Login</button>| <button type="button" class=" btn-link" data-toggle="modal" data-target="#regist">Regist</button>
        </dir>
      
      <?php
    }
    else
    {
      ?>
        <dir class="navbar-right">
            <a href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
        </dir>
        <div class="col-sm-4 navbar-brand">
          <a href="<?php echo $this->baseUrl(); ?>/auth/home"><?php echo $this->user['name'];?></a>
        </div>
        <div class="col-sm-4">
          <img class="navbar-brand img-circle" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
        </div>
        
    <?php
    }
    ?>
    </div>
  </div>
</nav>

<!-- end nav -->

<br />

<div id="view-content" class="container">
	<!-- <p>View script for controller <b>Matrial</b> and script/action name <b>index</b></p> -->
	<h3><?php echo $this->course[0]['name'] ;?> Course</h3><br><br>
	<?php 
	//var_dump($this->course) ;
	//var_dump($this->courseMatrial) ; 
	$courseMatrial = $this->courseMatrial ;
	$MaterialcommentsBlocks= $this->MaterialcommentsBlocks ;  
	$cid = $this->course[0]['id'] ;
	$baseUrl = $this->baseUrl() ;
	$editComId = $this->editComId;
	$addform =$this->addform ;

	//global
	?>

	<a href="<?php echo $baseUrl.'/Matrial/add?cid='.$this->course[0]['id'].'&cname='.$this->course[0]['name'] ?>" class="addlink" >Add Matrial</a><br/><br/> 

	<div class="row">
		<div class="sidebar col-sm-3"><h4>Matrial Types </h4><br>
			<ul>
			<a href="<?php echo $baseUrl.'/Matrial/?cid='.$this->course[0]['id'].'&type=pdf' ?>"><li>PDF</li></a>
			<a href="<?php echo $baseUrl.'/Matrial/?cid='.$this->course[0]['id'].'&type=doc' ?>"><li>doc</li></a>
			<a href="<?php echo $baseUrl.'/Matrial/?cid='.$this->course[0]['id'].'&type=ppt' ?>"><li>ppt</li></a>
			<a href="<?php echo $baseUrl.'/Matrial/?cid='.$this->course[0]['id'].'&type=zip' ?>"><li>zip</li></a>
			<a href="<?php echo $baseUrl.'/Matrial/?cid='.$this->course[0]['id'].'&type=mp4' ?>"><li>vedio</li></a>
			</ul>
		</div> 
		<div class="content col-sm-8">
		<?php function showMatrail ($type,$courseMatrial,$baseUrl,$commentform,$cid,$editComId,$addform,$MaterialcommentsBlocks) { ?>
			<h4><?php echo $type ?></h4><hr/>
			<?php  

			for($i=count($courseMatrial)-1 ; $i>=0; $i--){
				if($courseMatrial[$i]['type'] == $type){
					//echo '<img src="'.$this->baseUrl().'images/icons/pdf.ico"/>' ;
					$mid = $courseMatrial[$i]['id'] ;
			?>
			
					<div class="panel panel-default">
						<div class="panel-heading"><?php echo $courseMatrial[$i]['path']; ?>
							<div class="actions">
								<button type="button" class="link" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-edit"><span>Edit
								</button>
								&nbsp;&nbsp;
								<!-- Modal -->
								<div id="myModal" class="modal fade" role="dialog">
									<div class="modal-dialog">
									    <!-- Modal content-->
									    <div class="modal-content">
										    <div class="modal-header">
										        <button type="button" class="close" data-dismiss="modal">&times;</button>
										        <h4 class="modal-title">Edit Material</h4>
										    </div>
										    <div class="modal-body">
										        <p><?php
										        	$addform->setDefault('description',$courseMatrial[$i]['description']) ;										        	
										        	$addform->setDefault('hiddenpath',$courseMatrial[$i]['path']);

										        	$addform->setAction($baseUrl.'/Matrial/edit?mid='.$mid.'&type='.$type.'&cid='.$cid) ;
										        	echo  $addform ; ?>
										        </p>
										    </div>
										    <div class="modal-footer">
										    </div>
										</div>
									</div>
								</div>

								<!-- end of model - -->
								<a href="<?php echo $baseUrl.'/Matrial/delete?mid='.$mid.'&type='.$type.'&cid='.$cid ; ?>">
									<span class="glyphicon glyphicon-trash" ></span>Delete 
								</a>
								&nbsp;&nbsp;
								<?php 
								if($courseMatrial[$i]['enabledownload']){
									echo '<a href="'.$baseUrl.'/Matrial/lock?l=0&type='.$type.'&cid='.$cid.'&mid='.$mid.'"><span class="glyphicon glyphicon-lock"><span>lock </a>&nbsp;&nbsp;' ;						
								}else{
									echo '<a href="'.$baseUrl.'/Matrial/lock?l=1&type='.$type.'&cid='.$cid.'&mid='.$mid.'">Unlock </a>&nbsp;&nbsp;' ;
								}				
								if($courseMatrial[$i]['isshow']){
									echo '<a href="'.$baseUrl.'/Matrial/visible?v=0&type='.$type.'&cid='.$cid.'&mid='.$mid.'"><span class="glyphicon glyphicon-eye-close"><span>hide </a>&nbsp; &nbsp;' ;
								}else{
									echo '<a href="'.$baseUrl.'/Matrial/visible?v=1&type='.$type.'&cid='.$cid.'&mid='.$mid.'"><span class="glyphicon glyphicon-eye-open"><span>show</a>&nbsp; &nbsp;' ;
								}
								?>
							</div>	
							<br/><br/>
							Description : <?php echo $courseMatrial[$i]['description']; ?>				
					</div>
					<div class="panel-body">
						<?php 
						for($j=0 ; $j<count($MaterialcommentsBlocks[$mid]); $j++){

								$uname = $MaterialcommentsBlocks[$mid][$j]['uname'];   
								$uphoto = $MaterialcommentsBlocks[$mid][$j]['photo'];  
								$combody = $MaterialcommentsBlocks[$mid][$j]['body'] ;
								$comid = $MaterialcommentsBlocks[$mid][$j]['id'] ;
							?>

							<div class="well well-sm" style="background-color:;">
								<div class="actions">
									<a href="<?php echo $baseUrl.'/Comment/edit?type='.$type.'&cid='.$cid.'&comid='.$comid ?>">
										<span class="glyphicon glyphicon-edit"> <span>
									</a>

									<a href="<?php echo $baseUrl.'/Comment/delete?type='.$type.'&cid='.$cid.'&comid='.$comid ?> ">
										<span  class="glyphicon glyphicon-trash" ><span>
									</a>
								</div>
								<div class="row">
								    <div class="userinfo col-sm-2">
								    	<img src="<?php echo $baseUrl.'/images/'.$uphoto ?>"  width="30px" height="30px"/>
								    	<!-- <span><?php //echo $uname ?> : </span> -->
								    	<?php echo $uname ?> :
								    </div>
								    <div class="commentbody col-sm-9">
									<?php if($editComId == $comid) { ?>
										
											<form action="<?php echo $baseUrl.'/Comment/edit?type='.$type.'&cid='.$cid.'&comid='.$comid ?>" method="post">
												<div class="col-sm-10">
													<input type="text" name="commentbody" require class="form-control" value="<?php echo $combody ?>" />
												</div>
												<input type="submit" class="btn btn-success" value="save" >
											</form>
										
									<?php }else { ?>
										<span style="margin-left: 20px;"><?php echo $combody ?></span>
									<?php } ?>
									</div>
								</div>
							</div>

						<?php } ?>

						<form action="<?php echo $baseUrl.'/Comment/add?mid='.$mid.'&cid='.$cid.'&type='.$type ?>" method="post">
							<div class="col-sm-11">
								<input type="text" name="commentbody" require class="form-control" />
							</div>
							<input type="submit" class="btn" value="add" >
						</form>
					</div>

				</div>
				<?php 
				}			
			}
			?>
		<hr/>
		<?php 
		} showMatrail ($this->type,$courseMatrial,$baseUrl,$this->commentform,$cid,$editComId,$addform,$MaterialcommentsBlocks) ;
		?>
	</div>

</div>
