<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
      <div class="navbar-header active">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>"><span class="glyphicon glyphicon-home"> </span> Home</a>
      </div>
      <?php 
        if($this->user['type'] == "admin")
        {
          ?>
      <li><a href="<?php echo $this->baseUrl(); ?>/admin">Admin</a></li>
      <?php
    }
    ?>
   <!--  <li>
         <a href="<!?php echo $this->baseUrl(); ?>">
          <span class="glyphicon glyphicon-tasks"> </span> Courses</a>

    </li> -->
     <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <?php
          foreach ($this->categories as $category) {
        ?>
          <li><a href="<?php echo $this->baseUrl(); ?>/course/list?id=<?php echo $category['id'] ?>"><?php echo $category['name'] ?> </a></li>
          <?php } ?>
        </ul>
      </li>
    </ul>
    </div>
    <div class="col-sm-3">
      
      <?php if(!$this->logged){
        ?>
     
        <dir class="navbar-right">
            <button type="button" class=" btn-link" data-toggle="modal" data-target="#login" ><span class="glyphicon glyphicon-log-in"></span> Login</button>| <button type="button" class=" btn-link" data-toggle="modal" data-target="#regist">Regist</button>
        </dir>
      
      <?php
    }
    else
    {
      ?>
        <dir class="navbar-right">
            <a href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
        </dir>
        <div class="col-sm-4 navbar-brand">
          <a href="<?php echo $this->baseUrl(); ?>/auth/home"><?php echo $this->user['name'];?></a>
        </div>
        <div class="col-sm-4">
          <img class="navbar-brand img-circle" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
        </div>
        
    <?php
    }
    ?>
    </div>
  </div>
</nav>

</br>
</br>
</br>

<!-- Booooody Html   -->
<?php if($this->logged) {?>
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">

    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="text-center">
                  <b><?php echo $this->materials['description'] ;?></b>

        </div>
      </div>

      <div class="panel-body">
        <table class="table">
        <?php
        $mid =$this->materials['id'];

            for($i =0 ; $i<count($this->MaterialcommentsBlocks[$mid]) ; $i++){
             // var_dump($this->MaterialcommentsBlocks[$mid][$i]['']) ;
                 $uname = $this->MaterialcommentsBlocks[$mid][$i]['uname'] ;
                 $photo = $this->MaterialcommentsBlocks[$mid][$i]['photo'] ;
                 $comid = $this->MaterialcommentsBlocks[$mid][$i]['id'] ;
                 $uid = $this->MaterialcommentsBlocks[$mid][$i]['uid'] ;
                 $combody = $this->MaterialcommentsBlocks[$mid][$i]['body'] ;
              ?>
              <tr>
                <td></td>
                <td><img src="<?php echo $photo ?>"  width="30px" height="30px" />&nbsp;<?php echo $uname ?></td>
                <td></td>
                <td colspan="2">            

                  <?php if($this->editComId == $comid) { ?>                  
                      <form action="<?php echo $this->baseUrl(); ?>/comment/edit/?comid=<?php echo $comid;?>&mid=<?php echo $mid;?>&type=<?php echo $this->materials['type'];?>&isuser=1" method="post">
                        <div class="col-sm-10">
                          <input type="text" name="commentbody" require class="form-control" value="<?php echo $combody ?>" />
                        </div>
                        <input type="submit" class="btn btn-success" value="save" >
                      </form>
                    
                  <?php }else { ?>
                    <b><?php echo $combody ; ?></b>
                  <?php } ?>



                
                </td>
                <td></td>
                <?php if($uid == $this->user['id']) {?>
                  <td>

                      <a href="<?php echo $this->baseUrl(); ?>/comment/edit/?comid=<?php echo $comid ;?>&mid=<?php echo $mid ;?>&type=<?php echo $this->materials['type'];?>&isuser=1">
                        <span class="glyphicon glyphicon-edit"><span>Edit 
                      </a>
           
                      <a href="<?php echo $this->baseUrl(); ?>/comment/del/?cmid=<?php echo $comid ;?>&mid=<?php echo $this->materials['id'];?>&type=<?php echo $this->materials['type'];?>">
                        <span class="glyphicon glyphicon-trash" ></span>Delete 
                      </a>
                  </td>
                <?php } 
                  else {?>
                  <!-- <td></td> -->
                  <?php }?>
                
              </tr>

              <?php }?>
              </table>
      </div>
      <div class="panel-footer">
        <form class= "form-inline" action="<?php echo $this->baseUrl().'/Comment/add?mid='.$this->materials['id'].'&cid='.$this->materials['course_id'].'&type='.$this->materials['type'].'&isuser=1' ?>" method="post">
                <label for="text">comment</label>
                <input id='ex5' type="text" name="commentbody" require class="form-control c" />
                <input type="submit" class="btn btn-primary" value="add" >            
            </form>
      </div>
    </div>
      
      

  </div>
      
</div>
<?php } ?>

<!-- Login Model Part -->

<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="login" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title"><code>Sign In</code></h3>
        </div>
        <div class="modal-body">
          <?php

                if(isset($this->errorMessage)){

                            echo $this->errorMessage;
                }?>
                <?php

                            echo $this->loginform;
                ?>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
</div>

    <!-- Login Registration Part -->
      
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="regist" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title"><code>Sign Up</code></h3>
        </div>
        <div class="modal-body">
                 <?php
                if(isset($this->errorMessage)){

                            echo $this->errorMessage;
                }?>
                <?php

                            echo $this->registform;
                ?>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
</div>
