<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
       <div class="navbar-header">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>">Home</a>
      </div>
      <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-users">All Users</a></li>
    </ul>
    </div>
    <div class="col-sm-1 navbar-brand">
    	<a href="<?php echo $this->baseUrl(); ?>/auth/home"><?php echo $this->user['name'];?></a>
    </div>
    <div class="col-sm-1">
    	<img class="navbar-brand" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
    </div>
    <div class="col-sm-1">
    	<a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link">Logout</a>
    </div>
  </div>
</nav>

<div class="text-center">
  <h3>
    <code>
      <?php echo $this->user['name'];?> profile
    </code>
  </h3>
</div>

</br>
</br>
<div class="text-left">
  <div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-3">
      <img class="navbar-brand" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>

    </div>
  </div>
  </br>
  </br>
  <div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-1">
      <code>
        Name :
      </code>
    </div>
    <div class="col-sm-1">
      <?php echo $this->user['name'];?>
    </div>
  </div>
  </br>
  <div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-1">
      <code>
        Email :
      </code>
    </div>
    <div class="col-sm-1">
      <?php echo $this->user['email'];?>
    </div>
  </div>
    </div>
  </br>
  <div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-1">
      <code>
        Gender :
      </code>
    </div>
    <div class="col-sm-1">
      <?php echo $this->user['gender'];?>
    </div>
      </div>
  </br>
  <div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-1">
      <code>
        Country :
      </code>
    </div>
    <div class="col-sm-1">
      <?php echo $this->user['country'];?>
    </div>
  </div>
  </div>
</div>
<div class="text-center">
  <a class="btn btn-success" href="<?php echo $this->baseUrl().'/User/edit/id/'.$this->users[$i]['id'] ?>">Edit</a>
</div>
