<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
      <div class="navbar-header active">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>"><span class="glyphicon glyphicon-home"> </span> Home</a>
      </div>
      <?php 
        if($this->user['type'] == "admin")
        {
          ?>
      <li><a href="<?php echo $this->baseUrl(); ?>/auth/home">User</a></li>
      <?php
    }
    ?>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Categories
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <?php
          foreach ($this->categories as $category) {
        ?>
          <li><a href="<?php echo $this->baseUrl(); ?>/course/list?id=<?php echo $category['id'] ?>"><?php echo $category['name'] ?> </a></li>
          <?php } ?>
        </ul>
      </li>
    </ul>
    </div>
    <div class="col-sm-3">
      
      <?php if(!$this->logged){
        ?>
     
        <dir class="navbar-right">
            <button type="button" class=" btn-link" data-toggle="modal" data-target="#login" ><span class="glyphicon glyphicon-log-in"></span> Login</button>| <button type="button" class=" btn-link" data-toggle="modal" data-target="#regist">Regist</button>
        </dir>
      
      <?php
    }
    else
    {
      ?>
        <dir class="navbar-right">
            <a href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
        </dir>
        <div class="col-sm-4 navbar-brand">
          <a href="<?php echo $this->baseUrl(); ?>/auth/home"><?php echo $this->user['name'];?></a>
        </div>
        <div class="col-sm-4">
          <img class="navbar-brand img-circle" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
        </div>
        
    <?php
    }
    ?>
    </div>
  </div>
</nav>

</br>


<!-- Booooody Html   -->
<?php if($this->logged) {?>
<div class="text-right">

  <button type="button" class=" btn-link" data-toggle="modal" data-target="#addM" ></span>Add material</button>
  
</div>
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
      <table class="table table-hover">
          <thead>
            <tr>
              <th><code>Description</code></th>

              <th></th>
              <th><code># of Downloads</code></th>
              <th> </th>
            </tr>
          </thead>
       <?php
              foreach ($this->materials as $material) {
              ?>
              <tr>
                <td><b><?php echo $material['description'] ?></b></td>
                <td></td>
                <td><?php echo $material['numdownloads'] ?></td>
                <td>
                    <a href="<?php echo $this->baseUrl(); ?>/matrial/indetails/?mid=<?php echo $material['id'] ?>" type="button" class="btn btn-danger" data-dismiss="modal">Details</a>
                    <a href="<?php echo $this->baseUrl(); ?>/matrial/view/?mid=<?php echo $material['id'] ?>" type="button" class="btn btn-warning" data-dismiss="modal">View</a>
                    <?php if($material['enabledownload']) {?>
                    <a href="<?php echo $this->baseUrl(); ?>/matrial/download/?mid=<?php echo $material['id'] ?>" type="button" class="btn btn-success" data-dismiss="modal">download</a>
                    <?php } ?>
                </td>
              </tr>

              <?php }?>

      </table>
  </div>

</div>
<?php } ?>

<!-- Login Model Part -->

<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="login" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title"><code>Sign In</code></h3>
        </div>
        <div class="modal-body">
          <?php

                if(isset($this->errorMessage)){

                            echo $this->errorMessage;

                }?>

                <?php

                            echo $this->loginform;
                ?>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
</div>

    <!-- Login Registration Part -->
      
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="regist" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title"><code>Sign Up</code></h3>
        </div>
        <div class="modal-body">
                 <?php

                if(isset($this->errorMessage)){

                            echo $this->errorMessage;

                }?>

                <?php

                            echo $this->registform;

                ?>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
</div>


<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="addM" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title"><code>Add Material</code></h3>
        </div>
        <div class="modal-body">
                 <?php

                if(isset($this->errorMessage)){

                            echo $this->errorMessage;

                }?>

                <?php
                            $URL=$this->baseUrl();
                            $URL=$URL."/matrial/add?course_id=".$this->courseID;
                            //var_dump($this->courseID);
                            $this->addmaterialform->setDefault('course_id',$this->courseID) ;
                            $this->addmaterialform->setAction($URL);
                            echo $this->addmaterialform;

                ?>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
</div>
