<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
       <div class="navbar-header active">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/Admin">Home</a>
      </div>
      <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-users">All Users</a></li>
      <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-categories">All Categories</a></li>
      <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-requests">All Requests</a></li>
    </ul>
    </div>
    