<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
       <div class="navbar-header active">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>">Home</a>
      </div>
      <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-users">Users</a></li>
      <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-categories">Categories</a></li>
      <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-requests">Requests</a></li>
    </ul>
  </div>
  <div class="col-sm-1 navbar-brand">
        <?php echo $this->user['name'];?>
      </div>
      <div class="col-sm-1">
        <img class="navbar-brand" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
      </div>
      <div class="col-sm-1">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link">Logout</a>
      </div>
    </div>
  </nav>
