<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
      <div class="navbar-header active">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>"><span class="glyphicon glyphicon-home"> </span> Home</a>
      </div>
      <?php 
        if($this->user['type'] == "admin")
        {
          ?>
      <li><a href="<?php echo $this->baseUrl(); ?>/auth/home">User</a></li>
      <?php
    }
    ?>
    <li>
          <a href="<?php echo $this->baseUrl(); ?>">
          <span class="glyphicon glyphicon-tasks"> </span> Courses</a>
    </li>
    </ul>
    </div>
    <div class="col-sm-3">
      
      <?php if(!$this->logged){
        ?>
     
        <dir class="navbar-right">
            <button type="button" class=" btn-link" data-toggle="modal" data-target="#login" ><span class="glyphicon glyphicon-log-in"></span> Login</button>| <button type="button" class=" btn-link" data-toggle="modal" data-target="#regist">Regist</button>
        </dir>
      
      <?php
    }
    else
    {
      ?>
        <dir class="navbar-right">
            <a href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
        </dir>
        <div class="col-sm-4 navbar-brand">
          <a href="<?php echo $this->baseUrl(); ?>/auth/home"><?php echo $this->user['name'];?></a>
        </div>
        <div class="col-sm-4">
          <img class="navbar-brand img-circle" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
        </div>
        
    <?php
    }
    ?>
    </div>
  </div>
</nav>
    <!-- ###############  end nav  ################## -->
<div class="container center">
  <table cellpadding="10" cellspacing="10" width="100%" height="100%">
    <tr>
      <td valign="top" width="15%" color="black">
        <br><br><br><br>
        <ul class="adminsidebar">
          <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-users">Users</a></li>
          <li class="active">
          	<a href="<?php echo $this->baseUrl();?>/Admin/list-categories">Categories</a>
          </li>
          <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-requests">Requests</a></li>
        </ul>
      </td>
      <td>
		<!-- ###############  Body  ################## -->
			<h1 align="center">All Categories</h1><br />
			<div class="table table-responsive" >
				<a href="<?php echo $this->baseUrl(); ?>/Admin/add-category"> Add Category </a>
				<table class="table table-hover table-bordered">
				    <thead>
				      <tr>
				      	<th>#</th>
				        <th>name</th>
				        <th>description</th>
				        <th>Actions</th>
				      </tr>
				    </thead>
				    <tbody>
				    	<?php if($this->categories) { 
							for($i=0; $i<count($this->categories); $i++){ 
								if($this->id&&$this->id==$this->categories[$i]['id']){
						?>
						<tr>
							<form method="post" action="<?php echo $this->baseUrl(); ?>/Category/edit/id/<?php echo $this->categories[$i]['id']; ?>">
					      	<td><?php echo $this->categories[$i]['id']; ?></td>
					      	<td>
					      		<input type="text" name="name" value="<?php echo $this->categories[$i]['name']; ?>"/>
					      	</td>
					      	<td>
					      		<textarea type="text" name="description"><?php echo $this->categories[$i]['description'];?></textarea>
					      	</td>
					        <td>
							    <input type="submit" class="btn btn-success" value="Save" />
							</td>
							</form>
						</tr>
						<?php }else{?>
				      	<tr>
					 		<td><?php echo $this->categories[$i]['id']; ?></td>
					      	<td><?php echo $this->categories[$i]['name']; ?></td>
					      	<td><?php echo $this->categories[$i]['description']; ?></td>
					        <td>
							    <a class="btn btn-success" href="<?php echo $this->baseUrl().'/Admin/list-categories/id/'.$this->categories[$i]['id'] ?>">Edit</a>
							    <a class="btn btn-danger" href="<?php echo $this->baseUrl().'/Category/delete/id/'.$this->categories[$i]['id'] ?>">Delete</a>
								<a class="btn btn-warning" href="<?php echo $this->baseUrl().'/Admin/category-courses/id/'.$this->categories[$i]['id'] ?>">Courses</a>
					        </td>
					    </tr>
					    <?php }}} ?>
				    </tbody>
				</table>
			</div>
	  <!-- ###############  end Body  ################## -->
      </td>
    </tr>
  </table>
</div>
