<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
       <li>
        <a href="<?php echo $this->baseUrl(); ?>/Admin">Home</a>
      </li>
      <li>
      	<a href="<?php echo $this->baseUrl();?>/Admin/list-users">Users</a>
      </li>
      <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-categories">Categories</a></li>
      <div class="navbar-header active">
      	<a class="navbar-brand" href="<?php echo $this->baseUrl();?>/Admin/list-requests">Requests</a>
      </div>
    </ul>
  </div>
  <div class="col-sm-1 navbar-brand">
        <?php echo $this->user['name'];?>
      </div>
      <div class="col-sm-1">
        <img class="navbar-brand" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
      </div>
      <div class="col-sm-1">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link">Logout</a>
      </div>
    </div>
  </nav>
<!-- ###############  Body  ################## -->
<div class="container center">
	<h1 align="center">All Requests</h1><br />
	<?php if($this->requests) { 
		for($i=0; $i<count($this->requests); $i++){ ?>
  			<div class="col-sm-4">
				<div class="panel panel-primary">
					<div class="panel-heading">there is a request from <?php echo  $this->requests[$i]['name'];?></div>
				  	<div class="panel-body">
				  		<?php echo  $this->requests[$i]['body'];?>
				  	</div>
				</div>
			</div>
    <?php }} ?>
	</div>
</div>