<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
       <div class="navbar-header active">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/Admin">Home</a>
      </div>
      <li ><a href="<?php echo $this->baseUrl();?>/Admin/list-users">All Users</a></li>
    </ul>
    </div>
    <div class="col-sm-1 navbar-brand">
    	<?php echo $this->user['name'];?>
    </div>
    <div class="col-sm-1">
    	<img class="navbar-brand" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
    </div>
    <div class="col-sm-1">
    	<a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link">Logout</a>
    </div>
  </div>
</nav>
<!-- ###############  Body  ################## -->
<div class="container center">
	<h1 align="center">All Users</h1><br />
	<div class="table table-responsive" >
		<a href="<?php echo $this->baseUrl(); ?>/User/add"> Add User </a>
		<table class="table table-hover table-bordered">
		    <thead>
		      <tr>
		      	<th>photo</th>
		        <th>name</th>
		        <th>email</th>
		        <th>type</th>
		        <th>gender</th>
		        <th>country</th>
		        <th>Actions</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<?php if($this->users) { 
					for($i=0; $i<count($this->users); $i++){ ?>
		      	<tr>
			      	<td><img src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->users[$i]['photo']; ?>" width="50px" height="50px"/></td>
			      	<td><?php echo $this->users[$i]['name']; ?></td>
			      	<td><?php echo $this->users[$i]['email']; ?></td>
			      	<td><?php echo $this->users[$i]['type']; ?></td>
			      	<td><?php echo $this->users[$i]['gender']; ?></td>
			      	<td><?php echo $this->users[$i]['country']; ?></td>
			        <td>
					    <a class="btn btn-success" href="<?php echo $this->baseUrl().'/User/edit/id/'.$this->users[$i]['id'] ?>">Edit</a>
					    <a class="btn btn-danger" href="<?php echo $this->baseUrl().'/User/delete/id/'.$this->users[$i]['id'] ?>">Delete</a>
						<a class="btn btn-warning" href="<?php echo $this->baseUrl().'/Admin/ban/id/'.$this->users[$i]['id'] ?>">ban</a>
						
			        </td>
			    </tr>
			    <?php }} ?>
		    </tbody>
		</table>
	</div>
</div>