<nav class="navbar navbar-inverse">
  <div class="container-fluid row">
    <div class="col-sm-9">
    <ul class="nav navbar-nav">
      <div class="navbar-header active">
        <a class="navbar-brand" href="<?php echo $this->baseUrl(); ?>"><span class="glyphicon glyphicon-home"> </span> Home</a>
      </div>
      <?php 
        if($this->user['type'] == "admin")
        {
          ?>
      <li><a href="<?php echo $this->baseUrl(); ?>/Admin">Admin</a></li>
      <?php
    }
    ?>
    <li>
          <a href="<?php echo $this->baseUrl(); ?>">
          <span class="glyphicon glyphicon-tasks"> </span> Courses</a>
    </li>
    </ul>
    </div>
    <div class="col-sm-3">
      
      <?php if(!$this->logged){
        ?>
     
        <dir class="navbar-right">
            <button type="button" class=" btn-link" data-toggle="modal" data-target="#login" ><span class="glyphicon glyphicon-log-in"></span> Login</button>| <button type="button" class=" btn-link" data-toggle="modal" data-target="#regist">Regist</button>
        </dir>
      
      <?php
    }
    else
    {
      ?>
        <dir class="navbar-right">
            <a href="<?php echo $this->baseUrl(); ?>/auth/logout" type="button" class=" btn-link"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
        </dir>
        <div class="col-sm-4 navbar-brand">
          <a href="<?php echo $this->baseUrl(); ?>/auth/home"><?php echo $this->user['name'];?></a>
        </div>
        <div class="col-sm-4">
          <img class="navbar-brand img-circle" src="<?php echo $this->baseUrl(); ?>/images/<?php echo $this->user['photo']; ?>"/>
        </div>
        
    <?php
    }
    ?>
    </div>
  </div>
</nav>

</br>
</br>
</br>
</br>
<?php if($this->logged){
        ?>
<div class="row">
  <div class="col-sm-1">
  
  </div>
  <div class="col-sm-4">
    <h3>
      <code>
        Send Your matrial request 
      </code>
    </h3>
  </div>
</div>
</br>
</br>
<div class="text-left row">
<div class="col-sm-1">
  
</div>
<div class="col-sm-4">
  <?php
  echo $this->requestform;
  ?>
</div>
  
</div>


<?php }
        ?>




      <!-- Login Model Part -->

<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="login" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title"><code>Sign In</code></h3>
        </div>
        <div class="modal-body">
          <?php

                if(isset($this->errorMessage)){

                            echo $this->errorMessage;

                }?>

                <?php

                            echo $this->loginform;
                ?>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
</div>

    <!-- Login Registration Part -->
      
<div class="container">
  <!-- Modal -->
  <div class="modal fade" id="regist" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header text-center">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title"><code>Sign Up</code></h3>
        </div>
        <div class="modal-body">
                 <?php

                if(isset($this->errorMessage)){

                            echo $this->errorMessage;

                }?>

                <?php

                            echo $this->registform;

                ?>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>
</div>